organization|non-profit|mod
southern poverty law center|organization|appo
organization|montgomery|in
founded|southern poverty law center|obj
founded|1970s|in
1970s|help|rel
help|1970s|subj
litigate|minorities|subj
abuses|civil rights|nn
litigate|abuses|against
block|same|post
located|block|in
block|dexter avenue baptist church|as
dexter avenue baptist church|which|whn
pastored|once|mod
was|pastored|pred
established|effectively|amod
established|center|subj
established|programs|obj
established|and|punc
established|implemented|conj
implemented|center|subj
implemented|actions|obj
decades|last|post
decades|three|amount-value
actions|decades|over
decades|fulfilling|towards
fulfilling|center|subj
mission|its|gen
fulfilling|mission|obj
initiative|core|nn
initiative|center|for
is|classroom|pred
program|started|vrel
started|program|obj
started|1991|in
called|program|subj
called|"|punc
tolerance|teaching|nn
called|tolerance|obj
tolerance|"|punc
tolerance|that|whn
involves|tolerance|subj
involves|more|obj
teachers|400,000|num
more|teachers|than
involves|and|punc
involves|includes|conj
includes|tolerance|subj
includes|materials|obj
materials|promoting|rel
promoting|material|subj
promoting|"|punc
understanding|interracial|mod
interracial|and|punc
interracial|intercultural|conj
promoting|understanding|obj
funds|also|mod-before
funds|splc|subj
funds|three-year|obj
program|$100,000|nn
program|civil rights|nn
program|litigation|nn
three-year|program|appo
program|georgia|in
georgia|designed|vrel
designed|georgia|obj
designed|stem|mod
stem|splc|subj
cutbacks|federal|mod
stem|cutbacks|obj
cutbacks|programs|in
programs|that|whn
provide|programs|subj
assistance|free|mod
assistance|legal|mod
provide|assistance|obj
people|poor|mod
assistance|people|to
actions|civil|mod
people|actions|in
produces|center|subj
report|intelligence|nn
produces|report|obj
report|magazine|conj
magazine|that|whn
tracks|magazine|subj
groups|hate|nn
tracks|groups|obj
magazine|and|punc
extremists|covers|nn
extremists|right-wing|nn
magazine|extremists|conj
center|law|nn
co-founder|center|gen
co-founder|and|punc
counsel|chief|mod
counsel|trial|mod
co-founder|counsel|conj
co-founder|morris dees|appo
handled|successfully|amod
handled|co-founder|subj
cases|civil rights|nn
handled|cases|obj
his|1973|num
lawsuit|his|gen
lawsuit|federal|mod
more than 30 years--|lawsuit|in
handled|had|mod
had|more than 30 years--|subj
effect|practical|mod
had|effect|obj
effect|forcing|of
forcing|more than 30 years--|subj
homes|funeral|nn
provide|homes|subj
services|equal|mod
provide|services|obj
services|blacks|to
blacks|and|punc
blacks|whites|conj
lawyer|white|mod
been|lawyer|as
been|instrumental|pred
instrumental|crusading|in
crusading|dees|subj
intolerance|racial|mod
crusading|intolerance|against
intolerance|using|by
using|lawsuits|obj
lawsuits|destroy|rel
destroy|lawsuit|subj
destroy|finances|obj
groups|hate|nn
finances|groups|of
won|1979|since
won|he|subj
won|series|obj
series|six|of
suits|countrywide|mod
suits|civil rights|nn
six|suits|conj
suits|ku klux klan|against
ku klux klan|and|punc
groups|other|mod
groups|neo-nazi|nn
ku klux klan|groups|conj
groups|accused|vrel
accused|groups|obj
activity|criminal|mod
accused|activity|of
secured|case|in
secured|dees|subj
secured|multi-million|obj
defendants|convicted|mod
judgments|defendants|against
put|effectively|amod
defendants|put|rel
put|defendant|subj
put|them|obj
put|business|out of
