producer|south america|gen
producer|leading|mod
producer|gold|nn
is|producer|pred
is|while|mod
production|its|gen
production|diamond|nn
while|ranks|comp1
ranks|production|subj
ranks|seventh|obj
seventh|world|in
export|peru|gen
export|chief|mod
is|copper|pred
copper|(|punc
copper|addition|in
addition|silver|rel
silver|addition|subj
addition|tin|conj
tin|and|punc
tin|iron|conj
is|)|punc
is|yet|mod
industry|gold|nn
's|industry|pred
began|only|mod-before
only|brazil|to
began|second|subj
began|resurgence|obj
resurgence|mid-90s|in
mid-90s|buoyed|vrel
buoyed|mid-90s|obj
buoyed|by|by-subj
investment|foreign|mod
buoyed|investment|by
discovered|1996|in
rich|especially|mod
seam|rich|mod
seam|ore|of
discovered|seam|obj
led to|that|subj
led to|country|obj
country|becoming|rel
becoming|country|subj
manufacture|world|gen
manufacture|eighth|post
manufacture|largest|mod
manufacture|gold|nn
becoming|manufacture|obj
manufacture|1998|in
was|2000|in
was|seventh|pred
was|industry|with
industry|expecting|rel
expecting|industry|subj
growth|continued|mod
expecting|growth|obj
investments|long-term|mod
growth|investments|due to
government|peruvian|mod
fined|government|subj
fined|south america|obj1
$500,000|largest|mod
$500,000|goldmine|nn
fined|$500,000|obj2
spill|mercury|nn
$500,000|spill|for
spill|that|whn
poisoned|spill|subj
poisoned|dozens|obj
villagers|andean|mod
dozens|villagers|of
leads|chile|subj
leads|world|obj
production|copper|nn
world|production|in
produced|1996|in
mines|private|mod
private|and|punc
private|state-run|conj
produced|mines|subj
total|combined|mod
produced|total|obj
metric tons|4.7 million|amount-value
total|metric tons|of
copper|refined|mod
metric tons|copper|of
projects|additional|mod
projects|mining|nn
copper|projects|with
projects|going into|rel
going into|project|subj
going into|operation|obj
going into|year|mod
reached|2000|by
copper|chile|gen
copper|gold|conj
gold|and|punc
production|silver|mod
gold|production|conj
reached|copper|subj
high|all-time|mod
reached|high|obj
expected|venezuela|in
venezuela|where|wha
reserves|gold|nn
represent|reserves|subj
represent|approximately|guest
represent|10%|obj
total|world|gen
10%|total|of
rates|future|mod
rates|production|nn
grow|rates|subj
grow|rapidly|mod
investment|massive|mod
rapidly|investment|thanks to
initiated|1998|in
indians|caracas|near
initiated|indians|subj
initiated|protest|obj
operations|planned|mod
operations|mining|nn
protest|operations|against
territory|their|gen
operations|territory|in
promised|they|obj
promised|previously|guest
promised|that|c
would|not|neg
mined|area|obj
mined|gold|for
gold|or|punc
gold|diamonds|conj
mine|diamond|nn
began|mine|subj
began|operations|obj
state|venezuelan|mod
operations|state|in
state|bolivar|of
bolivar|2001|in
began|expectations|with
expectations|becoming|of
becoming|mine|subj
mine|south america|gen
mine|second|post
mine|largest|mod
mine|diamond|nn
becoming|mine|obj
be|among|pred
be|world|among
top|inf|subj
producers|20|num
producers|gold|nn
top|producers|obj
producers|2000|by
projections|government|nn
top|projections|according to
