bertand piccard|swiss|mod
bertand piccard|balloonist|nn
abandon|bertand piccard|subj
attempt|his|gen
attempt|first|post
abandon|attempt|obj
attempt|circumnavigate|rel
circumnavigate|attempt|subj
circumnavigate|world|obj
world|non-stop|pnmod
hours|balloon|nn
hours|six|amount-value
non-stop|hours|in
hours|take-off|after
leak|fuel|nn
take-off|leak|because of
leak|january 12 , 1997|appo
attempt|his|gen
attempt|second|post
began|attempt|subj
began|january 28 , 1998|mod
way|his|gen
well|way|on
had|piccard|subj
had|abandon|fc
abandon|piccard|subj
abandon|attempt|obj
abandon|when|wha
refused|china|subj
refused|him|obj1
refused|entry|obj2
refused|causing|mod
causing|china|subj
causing|him|obj
causing|miss|mod
miss|out|mod
winds|needed|mod
out|winds|on
delays|trying|rel
trying|delay|subj
trying|get|fc
permission|fly-over|nn
get|permission|obj
permission|china|from
china|piccard|conj
piccard|and|punc
piccard|british|conj
brian jones|balloonist|nn
british|took off|rel
took off|british|obj
took off|brian jones|subj
'oex|chateau|nn
'oex|d|mod
took off|'oex|from
'oex|swiss alps|in
swiss alps|march 1 , 1999|on
attempt|third|post
swiss alps|attempt|for
drifted|they|subj
drifted|down|mod
down|north africa|to
north africa|crossed|vrel
crossed|north africa|obj
crossed|asia|toward
crossed|and|punc
passed over|with|mod-before
permission|prior|mod
passed over|permission|with
crossed|passed over|conj
passed over|north africa|subj
china|southern|mod
passed over|china|obj
stream|jet|nn
whisked|stream|subj
whisked|them|obj
whisked|pacific ocean|over
whisked|and|punc
grinded|then|mod-before
whisked|grinded|conj
grinded|stream|subj
halt|near|mod
grinded|halt|to
halt|central america|over
picked up|they|subj
stream|jet|nn
picked up|stream|obj
set|march 19|on
beat|record|rel
record|beat|obj
record|endurance|subj
set|beat|subj
set|just|guest
set|two weeks|obj
set|before|mod
morning|march 21|of
days|19|amount-value
morning|days|after
hours|21|amount-value
days|hours|conj
hours|and|punc
minutes|47|amount-value
hours|minutes|conj
piccard|balloonists|nn
piccard|and|punc
piccard|jones|conj
minutes|landed|rel
landed|minutes|obj
landed|piccard|subj
sands|saharan|nn
landed|sands|on
egypt|southern|mod
sands|egypt|of
winds|unfavorable|mod
prevented|winds|subj
landing|their|gen
landing|hoped-for|mod
prevented|landing|obj
landing|pyramids|near
crossed|they|subj
finish line|their|gen
degrees|9|amount-value
finish line|degrees|nn
finish line|longitude|nn
crossed|finish line|obj
crossed|day|mod
crossed|before|mod
crossed|setting|mod
setting|they|subj
setting|record|obj1
nonstop|first|post
record|nonstop|for
circumnavigation|hot-air balloon|nn
setting|circumnavigation|obj2
circumnavigation|globe|of
feat|their|gen
awarded|feat|for
awarded|anheuser-busch corporation|subj
awarded|balloonists|obj1
awarded|cup|obj2
cup|and|punc
money|$1 million|nn
money|prize|nn
cup|money|conj
money|some|whn
some|money|of
use|some|obj
use|they|subj
use|start|mod
start|they|subj
start|winds|obj
charity|hope foundation|nn
winds|charity|of
award|international olympic committee|subj
award|them|obj1
award|olympic order|obj2
