Since its August 1999 debut, San Mateo, California-based Napster has accumulated over 10 million users and three lawsuits.
Claiming Napster's only product, a free file-sharing application, encourages copyright infringement, the Recording Industry Association of America sued, seeking $100,000 for each song illegally traded.
The heavy-metal band Metallica sued Napster and three universities for copyright infringement and racketeering, seeking $10 million in damages.
The universities were dropped from the suit after agreeing to block the site from their computer networks.
Rapper Dr. Dre also filed a similar lawsuit.
Metallica's drummer hand-delivered a 60,000-page list of over 335,000 Napster users who allegedly offered copies of its songs illegally on the Internet, demanding they be blocked from the service.
Dr. Dre was to deliver a similar list of over 200,000.
Some recording artists and a number of production organizations have supported the plaintiffs.
Napster's supporters include recording artists, some of which receive sponsorship from the company.
Representatives of both sides of the controversy testified before the Senate Judiciary Committee.
It decided to stay out of the dispute, which has drawn heavy lobbying in Washington.
In August, a judge ordered Napster to stop permitting the exchange of copyrighted music, effectively shutting the service down.
Despite Napster's claims of protection by the Digital Millennium Copyright Act and the Audio Home Recording Act, the judge believed it to be responsible for egregious copyright infringement.
On appeal, Napster was granted a stay of the order.
The recording industry's appeal of the stay will be heard in October.
