()|seizing|since
seizing|power|obj
power|1988|in
rulers|myanmar|gen
rulers|military|mod
used|rulers|subj
labor|forced|mod
used|labor|obj
labor|torture|conj
torture|and|punc
torture|rape|conj
rape|maintain|rel
maintain|rape|subj
maintain|power|obj
leadership|junta|nn
includes|leadership|subj
general|senior|mod
includes|general|obj
general|than shwe|person
general|and|punc
general|general|conj
general|tin oo|person
elections|opposition party|nn
elections|nld won 1990|nn
elections|but|punc
elections|junta|conj
honor|elections|subj
honor|results|obj
leader|nld|nn
leader|and|punc
suu kyi|nobel peace|nn
suu kyi|laureate|mod
leader|suu kyi|conj
demanded|repeatedly|amod
demanded|leader|subj
demanded|convened|fc
convened|parliament|obj
released|political prisoners|obj
released|avail|to
vice chairman|nld|nn
vice chairman|tin oo|person
threatened|vice chairman|obj
threatened|arrest|with
pressured|britain|subj
pressured|regime|obj
regime|hold|rel
hold|regime|subj
hold|talks|obj
us|and|punc
us|eu|conj
placed|us|subj
sanctions|economic|mod
placed|sanctions|obj
sanctions|myanmar|on
myanmar|encourage|rel
encourage|myanmar|subj
encourage|negotiations|obj
anniversary|tenth|post
made|anniversary|prior to
takeover|myanmar|gen
takeover|military|mod
anniversary|takeover|of
500-900|about|num-mod
arrests|500-900|nn
arrests|political|mod
made|arrests|obj
made|including|mod
including|arrest|subj
including|members|obj
members|absdf|of
absdf|led|vrel
led|absdf|obj
led|by|by-subj
led|ko thein|by
dissidents|protested|vrel
protested|dissidents|obj
protested|bangkok|in
bangkok|and|punc
bangkok|bangladesh|conj
us|and|punc
countries|european|nn
us|countries|conj
boycotted|us|subj
international heroin conference|4th|mod
boycotted|international heroin conference|obj
international heroin conference|myanmar|in
trafficking|its|gen
trafficking|drug|nn
myanmar|trafficking|because of
trafficking|and|punc
record|poor|mod
record|human rights|nn
trafficking|record|conj
become|it|subj
source|world|gen
source|leading|mod
become|source|obj
source|heroin|of
heroin|and|punc
heroin|epicenter|conj
crisis|regional|mod
crisis|aids|nn
epicenter|crisis|of
government|myanmar|gen
reported|government|subj
500|over|num-mod
activists|500|nn
activists|anti-government|mod
reported|activists|obj
activists|surrendered|vrel
surrendered|activists|obj
surrendered|march 1999|in
groups|17|num
laid down|groups|subj
laid down|arms|obj
october|early|mod
seized|october|in
men|armed|mod
seized|peacefully|mod-before
seized|men|subj
seized|myanmar embassy|obj
myanmar embassy|bangkok|in
release|demanding|mod
bangkok|release|conj
release|political prisoners|of
political prisoners|and|punc
political prisoners|recognition|conj
elections|1990|num
recognition|elections|of
stormed|2000|in
guerrillas|burmese|mod
stormed|guerrillas|subj
hospital|thai|mod
stormed|hospital|obj
agreed|us|subj
agreed|accept|fc
accept|the us|subj
refugees|1,500|num
refugees|burmese|mod
refugees|student|nn
accept|refugees|obj
refugees|thailand|from
denied|myanmar|obj1
certification|us|nn
certification|anti-drug|mod
denied|certification|obj2
awarded|suu kyi|obj1
awarded|dublin|obj2
dublin|ireland freedom|appo
honor|city|nn
ireland freedom|honor|of
activism|her|gen
activism|pro-democracy|mod
honor|activism|for
