debut|its|gen
debut|august 1999|nn
accumulated|debut|since
napster|san mateo , california-based|mod
accumulated|napster|subj
10 million|over|num-mod
users|10 million|nn
accumulated|users|obj
users|and|punc
lawsuits|three|nn
users|lawsuits|conj
product|claiming napster|gen
product|only|mod
application|free|mod
application|file-sharing|mod
product|application|appo
encourages|product|subj
infringement|copyright|nn
encourages|infringement|obj
infringement|recording industry association of america|appo
recording industry association of america|sued|vrel
sued|recording industry association of america|obj
sued|seeking|mod
seeking|product|subj
seeking|$100,000|obj
traded|illegally|amod
seeking|traded|mod
traded|song|subj
metallica|heavy-metal|mod
metallica|band|nn
sued|metallica|subj
sued|napster|obj
napster|and|punc
universities|three|nn
napster|universities|conj
infringement|copyright|nn
universities|infringement|for
infringement|and|punc
infringement|racketeering|conj
sued|seeking|mod
seeking|metallica|subj
seeking|$10 million|obj
$10 million|damages|in
dropped|universities|obj
dropped|suit|from
suit|agreeing|after
agreeing|university|subj
agreeing|block|fc
block|site|obj
networks|their|gen
networks|computer|nn
site|networks|from
dre|dr.|title
filed|also|mod-before
filed|dre|subj
lawsuit|similar|mod
filed|lawsuit|obj
hand-delivered|metallica|gen
hand-delivered|drummer|nn
list|60,000-page|mod
blocked|335,000|over
users|napster|nn
users|who|whn
offered|allegedly|mod-before
offered|users|subj
offered|copies|obj
songs|its|gen
copies|songs|of
offered|illegally|mod
illegally|internet|on
offered|demanding|mod
demanding|they|obj
blocked|users|obj
blocked|service|from
dre|dr.|title
was|deliver|pred
list|similar|mod
deliver|list|obj
artists|recording|nn
artists|and|punc
artists|number|conj
organizations|production|nn
number|organizations|of
supported|artists|subj
supported|plaintiffs|obj
supporters|napster|gen
include|supporters|subj
artists|recording|nn
include|artists|obj
artists|some|whn
some|artists|of
receive|some|subj
receive|sponsorship|obj
sponsorship|company|from
representatives|sides|of
sides|controversy|of
testified|representatives|subj
testified|senate judiciary committee|before
decided|it|subj
decided|stay|fc
stay|it|subj
stay|dispute|out of
dispute|which|whn
drawn|dispute|subj
drawn|heavy|obj
heavy|lobbying|rel
lobbying|heavy|subj
lobbying|washington|in
ordered|august|in
ordered|judge|subj
ordered|napster|obj
napster|stop|rel
stop|napster|subj
stop|permitting|mod
permitting|judge|subj
permitting|exchange|obj
music|copyrighted|mod
exchange|music|of
shutting|effectively|amod
permitting|shutting|mod
shutting|service|obj
shutting|down|mod
claims|napster|gen
claims|protection|of
protection|digital millennium copyright act|by
digital millennium copyright act|and|punc
digital millennium copyright act|audio home recording act|conj
believed|judge|subj
believed|it|obj
be|responsible|pred
infringement|egregious|mod
infringement|copyright|nn
responsible|infringement|for
granted|appeal|on
granted|napster|obj1
granted|stay|obj2
stay|order|of
industry|recording|nn
appeal|industry|gen
appeal|stay|of
heard|appeal|obj
heard|october|in
