capabilities|iran|gen
capabilities|known|mod
capabilities|nuclear|mod
capabilities|late 1990s|in
consisted of|capabilities|subj
facilities|nuclear|mod
facilities|research|nn
consisted of|facilities|obj
consisted of|including|mod
including|capability|subj
facility|bonab|nn
including|facility|obj
iran|northwestern|mod
facility|iran|in
iran|and|punc
iran|power plant|conj
power plant|construction|under
help|russian|mod
construction|help|with
port|southern|mod
help|port|in
port|bushehr|of
feared|us|subj
feared|that|c
facility|bushehr|nn
provide|facility|subj
provide|iran|obj
iran|means|with
means|build|rel
build|means|subj
build|nuclear weapon|obj
us|and|punc
us|israel|conj
israel|which|whn
suspecting|israel|subj
suspecting|iran|obj
iran|trying|of
trying|produce|fc
produce|nuclear weapons|obj
opposed|us|subj
cooperation|russian-iranian|nn
cooperation|nuclear|mod
opposed|cooperation|obj
claimed|russia|subj
claimed|that|c
plant|bushehr|nn
was|purely|guest
was|for|pred
purposes|peaceful|mod
was|purposes|for
had|iran|subj
had|neither|punc
capability|technical|mod
had|capability|obj
capability|nor|punc
capability|intention|conj
intention|making|of
making|iran|subj
making|nuclear weapons|obj
russia|and|punc
russia|iran|conj
signed|russia|subj
signed|agreement|obj
agreement|1998|in
1998|promote|rel
promote|1998|subj
cooperation|nuclear|mod
promote|cooperation|obj
promote|and|punc
build|possibly|amod
promote|build|conj
build|1998|subj
build|more|guest
plants|nuclear power|nn
build|plants|obj
plants|iran|in
voiced|israel|subj
voiced|concern|obj
concern|agreement|over
feared|us|subj
feared|that|c
scouring|iran|subj
market|world|nn
scouring|market|obj
materials|nuclear weapon|nn
market|materials|for
officials|us|nn
officials|intelligence|nn
differed|officials|subj
differed|pace|on
developments|iran|gen
developments|nuclear|mod
pace|developments|of
developments|difficulties|because of
difficulties|monitoring|in
monitoring|official|subj
acquisition|iran|gen
monitoring|acquisition|obj
material|nuclear|mod
acquisition|material|of
material|and|punc
material|technology|conj
in1998|pakistan|gen
in1998|nuclear|mod
in1998|testing|nn
feared|in1998|after
feared|israel|subj
feared|that|c
share|pakistan|subj
capabilities|its|gen
share|capabilities|obj
capabilities|and|punc
capabilities|technology|conj
technology|iran|with
accused|also|mod-before
accused|israel|subj
accused|russia|obj
russia|china|conj
china|and|punc
china|north korea|conj
north korea|selling|of
selling|israel|subj
technology|iran|nn
selling|technology|obj
technology|and|punc
technology|expertise|conj
program|its|gen
program|nuclear weapons|nn
expertise|program|for
tested|iran|subj
missile|mid-range|mod
tested|missile|obj
missile|1998|in
hitting|israel|obj
israel|saudi arabia|conj
saudi arabia|and|punc
saudi arabia|turkey|conj
capable|and|punc
capable|potentially|mod
capable|capable|conj
considered|israel|subj
considered|developments|obj1
threat|long-range|mod
considered|threat|obj2
survival|israel|gen
threat|survival|to
reported|1999|in
newspaper|turkish|nn
reported|newspaper|subj
reported|that|c
intended|iran|subj
intended|carry out|fc
carry out|iran|subj
tests|nuclear|mod
carry out|tests|obj
tests|which|whn
denied|tests|obj
denied|iran|subj
