Starbucks Coffee has expanded and diversified its business in a number of ways.
In joint ventures with basketball legend Magic Johnson, Starbucks opened shops in the inner-city neighborhoods of Seattle's Columbia City, West Lost Angeles and New York's Harlem.
It joined with Time Inc. to publish Joe magazine, to be sold exclusively in Starbucks coffeehouses.
With The New York Times it agreed to sell the newspapers in American stores for three years in exchange for advertising promotion.
Starbucks teamed with online urban delivery service Kozmo.com for cross-marketing and in-store promotion.
Kozmo drop-boxes will be in Starbucks wherever the service operates.
Starbucks acquired San Francisco-based Pasqua Coffee, adding 56 outlets to its network.
It acquired high-quality tea maker Tazo, giving it a foothold in the specialty tea market.
It established a European beachhead by acquiring the Seattle Coffee Co. in the UK.
Starbucks purchased upscale music retailer Hear Music to continue its tradition of selling music CDs in its shops.
A rumored takeover offer for Williams-Sonoma Inc. was unsuccessful.
Starbucks created a consumer products division for its specialty items.
Most of them have been joint ventures: ice cream with Dreyer's Grand Ice Cream; bottled Frappuccino with Pepsi-Cola; and the supermarket distribution of its coffee with Kraft Foods.
It also announced a line of premium chocolates.
Starbucks will form a new subsidiary, Starbucks X, to direct its expansion into online sales with a web site that will sell gourmet food, kitchen products and home furnishings as well as coffee products and music.
