In 1996, Energy Resources Australia (ERA) requested approval for the Jabiluka uranium mine on the edge of the Kakadu National Park in the Northern Territory.
ERA's second uranium mine in the area would generate billions of US dollars in revenue and create 2,000 jobs.
Opposition parties, conservationists and local Mirrar Aboriginal people opposed the mine despite ERA assurances that it wouldn't adversely affect the area.
After a protracted legal battle and amid continuing protests, ERA received approval and began mine construction in June 1998.
Police reported hundreds of arrests as protesters blockaded the site, firebombed an ERA office, and infiltrated an ERA general meeting.
Two aboriginal protestors won the 1999 Goldman Environmental Prize for having delayed the mine project.
A UNESCO World Heritage Bureau delegation visited the area in October 1998 and concluded the Jabiluka mine would pose a severe danger to the cultural and natural values of the adjacent Kakadu National Park.
The report recommended the Kakadu World Heritage Area be declared endangered.
Australia's Environmental Minister denounced the report as biased and unsubstantiated.
The bureau gave the government until April 15, 1999 to provide a comprehensive rebuttal.
Meanwhile, the government allowed work to continue, despite UNESCO's recommendation it be halted.
Australia's rebuttal cited errors of science, law and logic, and declared UNESCO's findings inconsistent with the fact that another nearby mine has operated for 20 years without adverse impact.
While the conservative government continued to support the mine, opposition parties vowed to halt operations should they win upcoming elections.
