During 1999 and 2000, over 6100 lawsuits nationwide were filed, suing American Home Products Corp.
(AHPC) on the issue of serious heart problems caused by its diet-drug fen-Phen (a combination of fenfluramine and Phentermine) taken by over six million people.
Fenfluremine is marketed by Wyeth-Ayerst as Pondimin or dexfenfluramine, a similar drug sold by the company, as Redux.
In the first lawsuit, a women suffering from heart valve damage sued for $110 million but settled for $500,000.
In May 1999, a Texas women sued AHPC for her heart valve damage after taking fen-Phen for eight months.
She reportedly settled for less than 10% of the $23.3 million awarded by a jury.
At that time, AHPC reported that more than 2,600 lawsuits over the health effects of fen-Phen were pending.
A national settlement with AHPC was being discussed but it was only in preliminary stages.
The first full trial of a lawsuit involving the death of a fen-Phen patient occurred in Texas in May 1999.
At the time, lawyers said several fen-Phen deaths have been settled for about $4 -$5 million each.
Another Texas patient received $8-$9 million, the largest settlement to date for an individual.
Collective settlements were made to groups of citizens in New Jersey, Massachusetts, Texas and Mississippi in efforts to settle the lawsuits nationwide.
In August 2000, a federal judge approved a $3.75 billion national AHPC settlement of health claims against fen-Phen.
Users would receive up to $1.5 million for treatment and for future medical monitoring.
