Interferon is a protein isolated from human cells.
Researchers in China have succeeded in developing recombinant a-1b Interferon from healthy leukocyte cells.
Interferon beta-1a, known by the brand name Avonex is a genetically engineered replica of a naturally occurring human protein.
Interferon is expensive with a year's supply in some applications running as high as $18,000.
For many years, Interferon was the only approved drug for the treatment of hepatitis C. Its long-term effectiveness was from 20-40% for patients treated for six months.
A more effective treatment for hepatitis C was to use the drug ribavarin in combination with Interferon.
Interferon alpha-2b is used to treat viral diseases, including Ebola, and is also used to treat some cancer.
It is used to slow down the debilitating neurological disease, multiple sclerosis.
Interferon has also saved many children with life threatening growths, called hemangiomas by its ability to knock out a tumor's ability to recruit blood vessels from nearby tissues.
Interferon is known to produce flu-like side effects.
For some people, interferon treatment can be nearly as devastating as the disease it's meant to cure.
