Between early 1996 to late 2000, the Kenyan government initiated a number of programs to improve the educational level of its population.
The emphasis is on raising enrollment levels, increasing the learning of science subjects, furnishing conservation studios, emphasizing health issues, and making improvements in business and industrial knowledge.
Phase Two of a plan to increase enrollment rates in primary schools developed by the Kenyan and British governments is scheduled with approximately $30 million provided by the Overseas Development Authority.
It is aimed at training primary school head teachers.
Between 1990 and 1995, 23 percent of students dropped out before reaching grade five as a result of lack of adequate teachers and teaching facilities in many schools.
The Kenyan Minister for Education announced that his ministry would soon increase the salary of secondary school science subject teachers to attract more teachers to the career.
The government is providing family life education, issuing new guidelines to liberalize the education sector, and instituting a sex education program.
It has revised previous rulings to create a more conducive environment for the private sector to be involved in higher education.
An early childhood development program of $34 million for over one million children and parents has been implemented.
Kenya is also strengthening education and training programs for the disabled and for street children as well as giving second chances to dropouts.
It has issued new guidelines to procure textbooks and training equipment and is working with women's groups to improve women's status.
