Linda Tripp, a Pentagon employee whose secret tape recordings of Monica Lewinsky's telephone conversations with her about Lewinsky's affair with President Clinton triggered a criminal investigation of the President, was subpoenaed to testify before a grand jury.
It was Tripp's decision to turn in the tapes in the "best interest" of Lewinsky who had come to rely on Linda Tripp's advice in trying to deal with the ups and downs of her relationship with Clinton.
Allegedly, she had become a reluctant confidante of Lewinsky and was encouraged by a book publisher to tape the conversations and pass them on to independent prosecutor Ken Starr.
She had taken copious notes and saved e-mail copies that she provided to the jury, including advice to Monica Lewinsky not to clean a semen-stained dress, thus preserving genetic evidence of sexual relations with the President.
Linda Tripp baited a jury by providing information about Monica Lewinsky to lawyers in the Paul Jones lawsuit against President Clinton.
In her testimony, she said Monica Lewinsky encouraged her to lie under oath to cover up the relationship.
A federal judge ordered the White House to retrieve e-mails from the President, the First Lady and presidential aides concerning Tripp, the FBI files controversy, and Kathleen Willey.
A poll by Newsweek magazine says that 56% of those polled believe Linda Tripp's main motivation in taping her conversations with Monica Lewinsky was to get attention or make money through a book deal.
Forty-six percent believe the Clinton administration is obstructing justice.
