In July 1999, items of O.J.
Simpson's property and memorabilia, including his Heisman Trophy, were seized to help settle the $33.5 million civil wrongful death judgment won by the families of murder victims Nicole Brown Simpson and Ronald Goldman.
The auction of the items raised $430,000.
Simpson made an appearance promoting Justice Media legal referral service as a favor to a friend.
He was paid only expenses, since any income would have been seized to satisfy the civil judgment against him.
Simpson's lawyer announced that he would keep custody of his two young children in an agreement with their slain mother's family.
The Brown family denied reaching an agreement.
Nicole Brown Simpson's sister and her lawyer asked the state attorney general to investigate possible perjury charges against Simpson, claiming he lied during his civil trial when he testified that he never hit, struck, slapped or kicked his late ex-wife.
In June 2000, Simpson offered to take a lie detector test if someone put up a $3 million reward to catch his ex-wife's killer.
In July, Simpson was to go on the Internet to field questions from the public and try again to convince America that he didn't kill his ex-wife and Goldman.
His appearance on NBC's "Today" promoting his www.askoj.com sparked controversy.
His scheduled appearance on ABC's "The View" was cancelled after viewers protested.
Simpson tried unsuccessfully to block a television miniseries about the defense of his murder case.
In August 2000, Simpson moved to Florida with his two children.
